### ISSUE TITLE
Implement basic operators

### ISSUE THREAD

**Issue by KatonLuaces** [KatonLuaces/blastoff#11]

**Comment by squirrelsquirrel78** [comment]
Jason Kao is doing vert concat![selfie-0](https://i.imgur.com/XxKIxIW.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by squirrelsquirrel78** [comment]
Jason Kao completed vert concat

**Comment by squirrelsquirrel78** [comment]
![selfie-0](https://i.imgur.com/sFoguDE.jpg)
