### ISSUE TITLE
Empty product/logical product issues on reduce

### ISSUE THREAD

**Issue by jfisher18** [KatonLuaces/blastoff#22]
Empty products in reduce row mult do not work, see tests/test-reduce_rows2.bl
Reduce row mult does not work for logical, see tests/test-reduce_rows3.bl
Had to hard code in 1 as mult identity in [C function](https://github.com/KatonLuaces/blastoff/blob/main/graphblas.c#L491) — is there a way of doing this better?

**Comment by squirrelsquirrel78** [comment]
![selfie-0](https://i.imgur.com/OONeKwv.jpg)
