### ISSUE TITLE
No terminator error on test-range_from_vector

### ISSUE THREAD

**Issue by jfisher18** [KatonLuaces/blastoff#23]

**Comment by squirrelsquirrel78** [comment]
See message in messenger. Jason Kao signing off.![selfie-0](https://i.imgur.com/OL25noB.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by squirrelsquirrel78** [comment]
In case you were wondering, yes, I did dress up for work![selfie-0](https://i.imgur.com/KMOwq1a.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
